### ISSUE TITLE
Error message when calling all_flags() without a user is misleading

### ISSUE THREAD

**Issue by jbatchelor-atlassian** [launchdarkly/node-client#102]
Very minor but could save someone else some time in the future if fixed.

When calling all_flags() without a user object the log message is `all_flags() called in offline mode. Returning empty map.`

I don't think it'd be controversial to split the offline and user checks into to error messages.

**Comment by eli-darkly** [comment]
Thanks for spotting this and submitting a PR. The fix will go out in the next release.
