### ISSUE TITLE
Failing nsp check: check nsp/npm audit before publishing to npm

### ISSUE THREAD

**Issue by jagtesh** [launchdarkly/node-client#108]
The current version (5.2.0) has a dependency (stringstream@0.0.5) that is currently failing an nsp check. See the below screenshot:

![image](https://user-images.githubusercontent.com/27375/43853681-d500dd5e-9b0e-11e8-8417-255eab19701b.png)

The resolution is to update it to stringstream@0.0.6. I will attach a PR for this shortly.

Thanks,
Jag

**Comment by jagtesh** [comment]
Can you add `nsp`/`npm audit` to your build pipeline to check for vulnerabilities before publishing to npm?

**Comment by eli-darkly** [comment]
Fixed in the 5.2.1 release.
