### ISSUE TITLE
allFlagsState hangs when passing callback but no options

### ISSUE THREAD

**Issue by gabegorelick** [launchdarkly/node-client#114]
Even though the `options` parameter for `allFlagsState` is supposed to be optional [1], it's actually required when passing a callback:

```js
ldClient.allFlagsState(user, callback); // this hangs
ldClient.allFlagsState(user, {}, callback); // this works
```

[1] https://github.com/launchdarkly/node-client/blob/62903ce09aa3311cecd126baff327958fc075eed/index.d.ts#L550-L569

**Comment by eli-darkly** [comment]
Whoops, sorry, thanks for catching that. We'll have a fix out shortly.

**Comment by eli-darkly** [comment]
Should work now.
