### ISSUE TITLE
Retrieve user object ?

### ISSUE THREAD

**Issue by FezVrasta** [launchdarkly/node-client#139]
Hi, is there any equivalent to [get user](https://apidocs.launchdarkly.com/docs/get-user)?

I can't seem to find one.

**Comment by eli-darkly** [comment]
What you've linked to there is a REST API endpoint that is part of the LaunchDarkly application API, which lets you query all the things that you can see on your dashboard, like users and feature flags.

The LaunchDarkly Node SDK is not a client for that API— it doesn't interact with it at all. It uses a separate mechanism to receive feature flag data from LaunchDarkly, it provides a way to evaluate flags, and it sends analytics events (including user data) back to LaunchDarkly; that's all it does.

So, if what you want is a REST client for all the things that are described [here](https://apidocs.launchdarkly.com/v2.0/docs), the SDK isn't the tool for that. While the API isn't particularly complicated, so you could really use any HTTP client and then just parse the response as JSON, we also provide an OpenAPI (a.k.a. Swagger) specification that can be used with any of the many tools out there that will turn such a specification into a client object with methods like `getUser`, etc. (The specification is the same data that was used to generate the API documentation.) You'll find a link to the specification in the "API Overview" section of that page under "Open API (Swagger)".

**Comment by FezVrasta** [comment]
Thanks for the explanation!
