### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by eboto** [launchdarkly/node-client#43]
Would love to have some typescript typings for this library!

**Comment by dlau** [comment]
Great suggestion, glad to work with a pr on https://github.com/DefinitelyTyped/DefinitelyTyped if anyone has one.

As with the sister issue, we will be happy to take over maintaining the typings when our library interface is updated.

In the meantime I've filed an issue on our tracker!

**Comment by natebrennand** [comment]
I think this can be closed out?
See #60 - #63

**Comment by dlau** [comment]
Yep!
