### ISSUE TITLE
5x increase in steady state CPU usage after integrating library

### ISSUE THREAD

**Issue by eboto** [launchdarkly/node-client#44]
I haven't profiled the node app yet, but after integrating the library into our node app, we found a significant baseline increase in CPU usage in cloudwatch. Our service has a once-per-second run-loop, and we are checking the flag at the start of each loop.

Have you come to expect behavior like this? The spike represents the redeploy. Before and after the spike represent the version before and after integrating `node-client`. Usage goes from steady state 3% to steady state 15%: a 5x increase.

![screen shot 2016-08-17 at 4 53 30 pm](https://cloud.githubusercontent.com/assets/250233/17757696/b82e302c-649d-11e6-8b6a-c910dccfcec7.png)

**Comment by jkodumal** [comment]
We haven't seen behavior like this before-- could you provide a code sample showing how you're initializing the client? Is it possible that you're instantiating a new client at the start of each loop (the client should be a singleton)?

**Comment by eboto** [comment]
Hi J! Thanks for the response. It is not possible that we are instantiating the client at the start of each loop, as the client is always accessed through this class and method:

```typescript
class Factory {
    private static _qLDClient: Promise<LDClient>;

    private createLowLevelClient(): Promise<LDClient> {
      if (Factory._qLDClient === undefined) {
        const ldClient = LaunchDarkly.init(LAUNCH_DARKLY_KEY);
        Factory._qLDClient = new Promise<LDClient>((resolve) => {
          this._log.info('Initializing the Launch Darkly client...');
          const start = new Date().getTime();
          ldClient.once('ready', () => {
            const end = new Date().getTime();
            this._log.info(`Launch Darkly client initialized in ${end - start}ms.`);
            resolve(ldClient);
          });
        });
      }
      this._log.info(`Factory client is now:`, Factory._qLDClient);

      return Factory._qLDClient;
    }
}
```

Again, I haven't dug in further into our use-case; the code itself accesses the low level client through a wrapper class that we _do_ instantiate willynilly, but it seemed like a suspiciously high increase in CPU usage for 1 or 2 additional object allocations per loop.

**Comment by spmason** [comment]
I can confirm this behaviour - it just happens as soon as you call `init` to create a new client so it pretty easy to replicate.  I see a constant 2-10% cpu tax just from initing an offline client.

However, if I edit the `index.js` to remove this line we get our cycles back:

```
  // TODO keep the reference and stop flushing after close
  setInterval(client.flush.bind(client), client.flush_interval * 1000).unref();
```

It looks like there's a typo here and the configuration should come from `config.flush_interval` - the code as it is effectively ends up with a `setInterval` of 0 - which causes `flush` to be called _a lot_ - even if most of the time the queue is empty

I've opened https://github.com/launchdarkly/node-client/pull/52 which fixes the issue
