### ISSUE TITLE
Offline flags should be undefined, not null

### ISSUE THREAD

**Issue by ericclemmons** [launchdarkly/node-client#57]
This way, you can take advantage of default args for clean defaults:

```js
const defaultFlags = {
  "testing": "Oy! I use this when testing!",
};

ldClient.all_flags(
  user,
  (err, flags = defaultFlags) => err ? reject(err) : resolve(flags)
);
```

Alternatively, support:

```js
const ldClient = new LaunchDarkly.init(process.env.LAUNCHDARKLY_TOKEN, {
  offline: process.env.NODE_ENV === "test" ? { ... } : false,
});
```

But that would conflict with the `.variation(...)` default value signature, so...nah.

**Comment by dlau** [comment]
Hi Eric, thanks for your suggestion.

This feels like it would require a major npm version bump, as some users may be checking for a `=== null` . Sound fair to revisit this when we have a larger change that requires a bump to `4.x`?
