### ISSUE TITLE
Promise interface?

### ISSUE THREAD

**Issue by ericclemmons** [launchdarkly/node-client#58]
I haven't been able to use https://github.com/sindresorhus/pify successfully with this library (`this` binding issues?), but I was wondering if, **in absence of a callback**, method calls could return a Promise so that we can use `async` & `await`.

Sounds cool, right!? ;)

**Comment by dlau** [comment]
Hi Eric, thanks for your report. I'm looking into your issue with using https://github.com/sindresorhus/pify .

Will discuss with the team about a promise interface. At first glance, it sounds like a great feature enhancement.

**Comment by yamoo** [comment]
Hi @apucacao,
I have tried Promise way with `variation` method but I couldn't receive the flag value on the args of then. It returns `undefined`. I also checked the promise value returned by the variation method with console.log. It shows `Promise { <pending> }` on my terminal. Do you have any advices for that? I'm using Node v8.7.0 and ldclient-node v3.3.0. Thank you.

**Comment by apucacao** [comment]
Hi @yamoo !

Sorry about that — there's a bug in the the code. I filed https://github.com/launchdarkly/node-client/issues/75 and we'll release a bug fix version shortly.

I'll let you know once I've released the fix.

Thanks for your patience!
Alexis

**Comment by apucacao** [comment]
@yamoo I just released version 3.3.1 which includes a fix for the bug you found. Thanks for reporting it and sorry for the inconvenience!

**Comment by yamoo** [comment]
@apucacao Thank you for the quick response! I could confirm it was fixed by upgrading to v3.3.1.
