### ISSUE TITLE
LDClient Typescript typing does not have an on() method

### ISSUE THREAD

**Issue by robertmassaioli** [launchdarkly/node-client#65]
See: https://github.com/launchdarkly/node-client/blob/master/index.d.ts#L327

According to the ["Initializing the client" documentation](http://docs.launchdarkly.com/docs/js-sdk-reference#section-initializing-the-client) we should be waiting for the on('ready', callback) event to fire before using the LDClient#variation method. If this is the case then the typescript typing is missing the on method.

We should just add the typings for the on method so that typescript users don't have to write code that essentially says "trust me, there is an on() function that you can use here":

    (<any>ldClient).on('ready', () => {

**Comment by apucacao** [comment]
Hi @robertmassaioli ,

Thanks for bringing this up. We'll add the missing function shortly.

Best,
Alexis

**Comment by apucacao** [comment]
Looking at this again, since `LDClient` extends `EventEmitter`, `on` should be already be defined. In fact VSCode autocompletes all the emitter methods in addition to the client methods. Does it not do that for you?
