### ISSUE TITLE
client.variation should not release zalgo

### ISSUE THREAD

**Issue by jvivs** [launchdarkly/node-client#69]
[`client.variation`](https://github.com/launchdarkly/node-client/blob/c4f67e73ffbc727eef718ef4c196bc22a2c0af8e/index.js#L129) has an error-first callback interface, it unfortunately does not appear to follow the pattern completely. 

Instead of always calling callbacks asynchronously, callbacks in the `variation` method could be called either sync or async.

This is a serious issue that introduces inconsistencies in code execution and impedes the ability for consumers to be able to reason about your. Without following this pattern to the letter, you release [zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).

**Comment by apucacao** [comment]
Hi @jvivs ,

Thanks for bringing this up. This is important to get right. We're going to change the code to avoid this inconsistency.

**Comment by apucacao** [comment]
Hi @jvivs ,

Our latest release — which adds `Promise` support — fixes this problem altogether.

Thanks for bringing it up!

Best,
Alexis

**Comment by johnvh** [comment]
The convention for callbacks is to wrap them in a `process.nextTick()` to force async. This should be trivial to do, no?

It seems reasonable to me that, if you're going to support callbacks, you should fix this. Many still prefer to use callbacks over promises.

**Comment by apucacao** [comment]
Our `Promise`-based solution should be compatible with both callbacks and promises.

Is that not true? Did you run into an issue?
