### ISSUE TITLE
How are errors handled?

### ISSUE THREAD

**Issue by rosskukulinski** [launchdarkly/node-client#7]
I would expect the callback function passed to ld_client.get_flag() would follow the standard nodejs (err, data...) pattern.  Skimming the code, it looks like on HTTP error you simply use the default value.  That won't tell me if your service is having issues or if I've supplied invalid credentials.

**Comment by jkodumal** [comment]
That is an good point-- we will change the callback. The [Go client](https://github.com/launchdarkly/go-client/blob/master/ldclient.go#L342) does a much better job of this, and the nodejs idiom seems quite appropriate here.

**Comment by ttahmouch** [comment]
Adding to this, it would be great if [line 82](https://github.com/launchdarkly/node-client/blob/master/index.js#L82) became `cb(error, default_val);`, and [line 81](https://github.com/launchdarkly/node-client/blob/master/index.js#L81) and [line 143](https://github.com/launchdarkly/node-client/blob/master/index.js#L143) were suppress(ed/ible).

**Comment by jkodumal** [comment]
Switching to an error-first callback will require a new major version release, since it's an API-breaking change. The logging suppression can happen in a minor release-- which will likely go out tomorrow.

**Comment by jkodumal** [comment]
This is now in PR. As I mentioned, it'll be a major version release since it's an API breaking change. If you bump to this version and don't update your toggle calls everywher, feature flags will behave very badly, indeed-- so be cautious when upgrading to this version.

**Comment by jkodumal** [comment]
I've released this in version 1.0.0. Docs and quickstart are being updated too. 

Just to reiterate-- be sure to update your `toggle` calls when you bump to this version!
