### ISSUE TITLE
Provide a sync API for `variation`

### ISSUE THREAD

**Issue by premshree** [launchdarkly/node-client#70]
Hi there,

Per a previous conversation with Launch Darkly support re: the synchronous nature of LD client's function interface masquerading as asynchronous functions, I was told "All of the LDClient instance methods are synchronous but still provide the callback pattern."

While we can use the async functions to make sync calls because the callbacks are executed immediately, I'd like to request an explicit `variationSync` API for synchronous use. This would be super useful to us.

Relying on what are really async functions for sync behavior is very risky.

Please let me know if you have any questions. Happy to chat.

**Comment by ea-tal** [comment]
Was this feature developed?

**Comment by eli-darkly** [comment]
@ea-tal It was not, but there's been further discussion on https://github.com/launchdarkly/node-server-sdk/issues/177 and we have left that issue open as a way of notifying people if and when there is a change.
