### ISSUE TITLE
package.json points to tarballs

### ISSUE THREAD

**Issue by premshree** [launchdarkly/node-client#73]
Hi there,

The `package.json` for `node-client` references tarballs directly for [`requestify` and `tunnel`](https://github.com/launchdarkly/node-client/blob/master/package.json#L31-L32). Is there a reason for this?

The reason we discovered this was, tangentially, because of how [Artifactory](https://www.jfrog.com/artifactory/) resolves external dependencies, though I'm not (yet) confident what the specific issue was.

**Comment by apucacao** [comment]
Hi @premshree ,

We had to fork `requestify` and `tunnel`, and we don't publish those to NPM. 

What issue are you running into?

**Comment by apucacao** [comment]
Let us know if you run into any issues in the future — I'm closing this for now.

**Comment by seanparmelee** [comment]
@apucacao, this can cause a problem for folks using npm 5.6: https://github.com/npm/npm/issues/19356

I didn't notice any commits in https://github.com/launchdarkly/node-tunnel; seems like it may be safe to use the published `tunnel` for now?

**Comment by apucacao** [comment]
Thanks for that. Look like we should indeed be able to simply use the published version.
