### ISSUE TITLE
Not polling updates

### ISSUE THREAD

**Issue by phun-ky** [launchdarkly/node-client#74]
With this code:

    'use strict';
    /*eslint no-console:0 quotes:0*/

    import launchDarkly from 'ldclient-node';
    import Bunyan from 'bunyan';
    import winston from 'winston';
    const logger = new Bunyan({ name: 'Server' });
    const ldclient = launchDarkly.init('<my key>', {
      logger: new winston.Logger({
        level: 'debug',
        transports: [new winston.transports.Console()]
      }),
      stream: false,
      timeout: 3
    });

    ldclient.once('ready', function() {
      console.log('ldclient ready');
      ldclient.variation('<myflag>', { key: 'user@test.com' }, false, function(err, showFeature) {
        console.log(err);
        if (showFeature) {
          console.log('SHOW FEATURE', showFeature);
        } else {
          console.log('HIDE FEATURE', showFeature);
        }
      });
    });

    ldclient.once('error', function(err) {
      console.log(err);
    });

I only get the console.log for SHOW/HIDE FEATURE once, even though I see the polling log flood. I am enabling/disabling the feature flag in the dashboard, nothing happens..

**Comment by apucacao** [comment]
Also, I'm curious why you decided to use polling mode here. We generally recommend streaming instead of polling since it offers many benefits like instant updates of your flag configurations in your app.

Happy to answer any questions as well :)

**Comment by phun-ky** [comment]
Reason I used polling is because the streaming method did not work. I started the file, just like the code mentioned, it registered the first feature variation and then silent. When I toggle the feature the first time, I get the log : receive patch event or something. 
When I use the polling feature, I see at least the client is pulling every second, but no updates are registered even though I am toggling continuously.. 


Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Alexis Georges <notifications@github.com> Dato: 29.11.2017  22:21  (GMT+01:00) Til: launchdarkly/node-client <node-client@noreply.github.com> Ko: Alexander Vassbotn Røyne-Helgesen <alexander@phun-ky.net>, Mention <mention@noreply.github.com> Emne: Re: [launchdarkly/node-client] Not polling updates (#74) 
Also, I'm curious why you decided to use polling mode here. We generally recommend streaming instead of polling since it offers many benefits like instant updates of your flag configurations in your app.
Happy to answer any questions as well :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/launchdarkly/node-client","title":"launchdarkly/node-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/launchdarkly/node-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@apucacao in #74: Also, I'm curious why you decided to use polling mode here. We generally recommend streaming instead of polling since it offers many benefits like instant updates of your flag configurations in your app.\r\n\r\nHappy to answer any questions as well :)"}],"action":{"name":"View Issue","url":"https://github.com/launchdarkly/node-client/issues/74#issuecomment-348000135"}}}

**Comment by apucacao** [comment]
When you get a chance, could share the code you tried with streaming?

I think the reason polling didn't output updates is because `variation` is only called once. But I would like to understand why streaming wasn't working for you, so that you can start using that mode.

**Comment by phun-ky** [comment]
The streaming code is the same as th polling code, only without stream : false 
To clarify, when using polling, I see that the client polls for updates every second, what does that have to do with variations run once? Am I missing something? 


Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Alexis Georges <notifications@github.com> Dato: 29.11.2017  23:42  (GMT+01:00) Til: launchdarkly/node-client <node-client@noreply.github.com> Ko: Alexander Vassbotn Røyne-Helgesen <alexander@phun-ky.net>, Mention <mention@noreply.github.com> Emne: Re: [launchdarkly/node-client] Not polling updates (#74) 
When you get a chance, could share the code you tried with streaming?
I think the reason polling didn't output updates is because variation is only called once. But I would like to understand why streaming wasn't working for you, so that you can start using that mode.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/launchdarkly/node-client","title":"launchdarkly/node-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/launchdarkly/node-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@apucacao in #74: When you get a chance, could share the code you tried with streaming?\r\n\r\nI think the reason polling didn't output updates is because `variation` is only called once. But I would like to understand why streaming wasn't working for you, so that you can start using that mode."}],"action":{"name":"View Issue","url":"https://github.com/launchdarkly/node-client/issues/74#issuecomment-348021438"}}}

**Comment by apucacao** [comment]
I mentioned that because in your original comment you said, "I only get the console.log for SHOW/HIDE FEATURE once…".

Were you seeing errors in the logs when using streaming?

**Comment by phun-ky** [comment]
Sorry for the late reply, I've managed to do what I want with this code (this code is to fetch flags and decide server routes on my node backend:

    /**
     * The event handler for featuerToggle
     * @type {FeatureFlagEventsEmitter}
     */
    export const featureFlagEvents = new FeatureFlagEventsEmitter();

    logger.info(
      `Attempting to initialize Launch Darkly initialized with sdk key: ${process.env.FEATURE_TOGGLE_LAUNCH_DARKLY_SDK_KEY}`
    );

    if (process.env.FEATURE_TOGGLE_LAUNCH_DARKLY_SDK_KEY) {
      featureToggleClient = require('ldclient-node').init(process.env.FEATURE_TOGGLE_LAUNCH_DARKLY_SDK_KEY, {
        timeout: 3,
        stream: false
      });

      featureToggleClient.once('ready', function() {
        logger.info(`Launch Darkly initialized with sdk key: ${process.env.FEATURE_TOGGLE_LAUNCH_DARKLY_SDK_KEY}`);
        setInterval(() => {
          featureToggleInterval = featureToggleClient.all_flags({ key: 'user@default.com' }, processFlags);
        }, 30000);
      });
    }

In the first versions of this code, `stream: true` was set, but that stopped working somehow, so I had to swtich to `stream:false`, and then it worked.

Which is weird because this code (that is used in an API route) works with streaming:

    const featureToggleClient = require('ldclient-node').init(process.env.FEATURE_TOGGLE_LAUNCH_DARKLY_SDK_KEY, {
      // this is seconds..
      timeout: 3
    });

    const fetchAllFlags = () => {
      return new Promise((resolve, reject) => {
        featureToggleClient.once('ready', function() {
          featureToggleClient.all_flags({ key: 'user@default.com' }, (err, flagMap) => {
            if (err) {
              reject(err);
            }
            resolve(processFlagsWithoutEmit(err, flagMap));
          });
        });
      });
    };

    fetchAllFlags()
      .then(flags => {
        logger.info('Feature flags fetched!');
        featureToggleClient.close();
        return res.status(200).json(flags);
      })
      .catch(err => {
        logger.warning(`Error fetching feature flags, returning default flags! ${JSON.stringify(err)}`);
        featureToggleClient.close();
        return res.status(200).json(flags);
      });

**Comment by apucacao** [comment]
Hi @phun-ky ,

I'm sorry for the late response here.

Are you still unable to use streaming in both of your use cases? When you try streaming mode, do you get any errors from the SDK?

Also, as a side note, we've released a newer version of the SDK with a few improvements, one of which is clearer errors.
