### ISSUE TITLE
Unhandled promise rejection when flushing events

### ISSUE THREAD

**Issue by jbunton-atlassian** [launchdarkly/node-client#85]
`client.flush` returns a promise but nothing is attached to handle rejections. This is deprecated in Node and in the future will cause the process to exit in a similar manner to an unhandled exception.

In our production services we have already configured unhandled rejections to cause a process exit. I noticed this bug because timeouts in the LaunchDarkly client are causing our processes to die when there is a network timeout.

I've created a demo repo if you want to try this out:
https://github.com/jbunton-atlassian/launchdarkly-bug-promise-rejection

It hardcodes a black hole IP address to simulate a timeout. Run it with the `SDK_KEY` and `FEATURE_KEY` environment variables. After a few seconds the automatic flush will trigger and you'll see the promise rejection warning.

Thanks :)

**Comment by apucacao** [comment]
Hi @jbunton-atlassian ,

Thanks for reporting this. And sorry for the inconvenience. We're going to put a fix out shortly to address this.

I'll keep you posted here.

**Comment by jbunton-atlassian** [comment]
Awesome! Thanks for the quick fix :D

**Comment by eli-darkly** [comment]
The 4.0.3 release should fix this, and I tested it in your sample code, but please feel free to reopen the issue if something still doesn't look right.
