### ISSUE TITLE
Crypto NPM module deprecated

### ISSUE THREAD

**Issue by cwill** [launchdarkly/node-client#92]
This package is still using the `crypto` package from npm, which has been replaced by a builtin module [and is deprecated](https://www.npmjs.com/package/crypto).  It should be removed and the builtin one used instead to avoid security vulnerabilities.

**Comment by eli-darkly** [comment]
Hi - sorry this fell off the radar for a while. I've verified that the built-in module is present in all versions of Node that we support, so we'll make this change ASAP.

**Comment by eli-darkly** [comment]
Fixed in version 5.1.2. Thanks for bringing this to our attention.

**Comment by cwill** [comment]
Thanks!
