### ISSUE TITLE
Vulnerability Detected in Node Dependency

### ISSUE THREAD

**Issue by AlexisGlez** [launchdarkly/node-client#97]
I ran some security reports in my application that now is using this node-client; the report found a `High severity` vulnerability in one of the dependencies of this module.

![image](https://user-images.githubusercontent.com/13372889/41477644-8613870e-708a-11e8-886e-2ae2d771b72a.png)

The fix should be very simple, just update the `original` dependency to version `original@1.0.1`.

Hopefully this won't be a breaking change.

More information in: https://snyk.io/test/npm/ldclient-node/5.0.1?tab=issues

**Comment by jkodumal** [comment]
Thanks @AlexisGlez -- this should be a relatively simple change that we'll try to address as soon as possible.

**Comment by AlexisGlez** [comment]
Thanks @jkodumal, really appreciate it 😄

**Comment by eli-darkly** [comment]
Rather than upgrading `original` I think we'll just drop it - we ended up not actually using that functionality.

**Comment by eli-darkly** [comment]
Fixed in version 5.0.2.
